/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package twitter;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.ui.RefineryUtilities;
import statistics.PieChart;
import statistics.StatisticalBarChart;

import twitter.classifier.Classifier;
import twitter.classifier.KNN;
import twitter.classifier.NaiveBayes;
import twitter.classifier.KeyWords;


/**
 *
 * @author omar
 */
public class Apps extends javax.swing.JFrame {

    /**
     * Creates new form Apps
     */
    public Apps() {
        initComponents();
        choice2.add("aucune");
        choice2.add("KeyWords");
        choice2.add("KNN");
        choice2.add("naive Bayes Presence Unigramme");
        choice2.add("naive Bayes Presence Bigramme");
        choice2.add("naive Bayes Presence Unigramme + Bigramme");
        choice2.add("naive Bayes frequence Unigramme");
        choice2.add("naive Bayes frequence Bigramme");
        choice2.add("naive Bayes frequence Unigramme + Bigramme");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tresult = new javax.swing.JTextArea();
        label2 = new java.awt.Label();
        panelG = new javax.swing.JPanel();
        jitem = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        numberOfTweet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        choice2 = new java.awt.Choice();
        button1 = new java.awt.Button();
        label1 = new java.awt.Label();
        button2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(6, 119, 252));
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Tresult.setBackground(new java.awt.Color(226, 235, 240));
        Tresult.setColumns(20);
        Tresult.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        Tresult.setRows(5);
        Tresult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(Tresult);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(1, 21, 1));
        label2.setText("TWEETS ANALYSIS");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1))
        );

        panelG.setBackground(new java.awt.Color(1, 71, 154));
        panelG.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jitem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitemActionPerformed(evt);
            }
        });

        button.setBackground(new java.awt.Color(151, 140, 138));
        button.setForeground(java.awt.Color.white);
        button.setText("Launch");
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        numberOfTweet.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        numberOfTweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfTweetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel1.setText("Methode de classification");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel2.setText("Thème");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel3.setText("Nombre de Tweets ");

        choice2.setBackground(new java.awt.Color(222, 222, 231));

        button1.setBackground(new java.awt.Color(22, 195, 125));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        button1.setLabel("Pie Chart");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 3, 24)); // NOI18N
        label1.setText("Stasitics");

        button2.setActionCommand("Bar Chart Error ratio");
        button2.setBackground(new java.awt.Color(22, 195, 125));
        button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button2.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        button2.setLabel("Bar Chart Error ratio");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGLayout = new javax.swing.GroupLayout(panelG);
        panelG.setLayout(panelGLayout);
        panelGLayout.setHorizontalGroup(
            panelGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelGLayout.createSequentialGroup()
                .addGroup(panelGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 54, Short.MAX_VALUE))
            .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jitem)
                    .addComponent(numberOfTweet)
                    .addComponent(choice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addComponent(button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelGLayout.setVerticalGroup(
            panelGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jitem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberOfTweet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choice2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberOfTweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfTweetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfTweetActionPerformed

    private void jitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jitemActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
    	TweetDataBase db = new TweetDataBase();
        List<Tweets> tweets = db.loadDBTweets();
    	SearchForTweets s = new SearchForTweets();
        var item = jitem.getText();
        int nbrTweets;
        nbrTweets = Integer.parseInt(numberOfTweet.getText());
        String strategy = choice2.getSelectedItem();
        s.getTweet(item,nbrTweets);
        ArrayList<Tweets> res;
        if(evt.getSource() != button){
        } else {
            Tresult.setText("");
            res=s.getResultsOfTweets();
            TweetDataBase a = new TweetDataBase();
            ArrayList<Tweets> loadDBTweets = a.loadDBTweets();
            
            for (int i=0 ;i<res.size();i++){
            
                switch (strategy) {
                    case "KeyWords":
                    {
                        KeyWords pol = new KeyWords(tweets,"databases/positive.txt","databases/negative.txt");
                        pol.classify(res.get(i));
                        //CountWord(res.get(i),"databases/negative.txt","databases/positive.txt");
                        Tresult.append(res.get(i).toString());
                        break;
                    }
                    case "aucune":
                    {
                        Tresult.append(res.get(i).toString());
                        
                        
                        //Tresult.append(loadDBTweets.get(i).toString());
                        break;
                    }
                    case "KNN":
                        {
                            
                            KNN knn = new KNN(loadDBTweets,5);
                            knn.classify(res.get(i));
                            //Tresult.append(database.toString());
                            Tresult.append(res.get(i).toString());
                            break;
                        }
                    case "naive Bayes Presence Unigramme":
                        {
                            
                            NaiveBayes nb = new NaiveBayes(loadDBTweets);
                            nb.classify(res.get(i), 1, 1);
                            Tresult.append(res.get(i).toString());
                            break;
                        }
                    case "naive Bayes Presence Bigramme":
                        {
                            //TweetDataBase a = new TweetDataBase();
                            //ArrayList<Tweets> database = a.loadDBTweets();
                            NaiveBayes nb = new NaiveBayes(loadDBTweets);
                            nb.classify(res.get(i), 1, 2);
                            Tresult.append(res.get(i).toString());
                            break;
                        }
                    case "naive Bayes Presence Unigramme + Bigramme":
                        {
                            //TweetDataBase a = new TweetDataBase();
                            //ArrayList<Tweets> database = a.loadDBTweets();
                            NaiveBayes nb = new NaiveBayes(loadDBTweets);
                            nb.classify(res.get(i), 1, 0);
                            Tresult.append(res.get(i).toString());
                            break;
                        }
                    case "naive Bayes frequence Unigramme":
                        {
                            //TweetDataBase a = new TweetDataBase();
                            //ArrayList<Tweets> database = a.loadDBTweets();
                            NaiveBayes nb = new NaiveBayes(loadDBTweets);
                            nb.classify(res.get(i), 0, 1);
                            Tresult.append(res.get(i).toString());
                            break;
                        }
                    case "naive Bayes frequence Bigramme":
                        {
                            //TweetDataBase a = new TweetDataBase();
                            //ArrayList<Tweets> database = a.loadDBTweets();
                            NaiveBayes nb = new NaiveBayes(loadDBTweets);
                            nb.classify(res.get(i), 0, 2);
                            Tresult.append(res.get(i).toString());
                            break;
                        }
                    case "naive Bayes frequence Unigramme + Bigramme":
                        {
                            //TweetDataBase a = new TweetDataBase();
                            //ArrayList<Tweets> database = a.loadDBTweets();
                            NaiveBayes nb = new NaiveBayes(loadDBTweets);
                            nb.classify(res.get(i), 0, 0);
                            Tresult.append(res.get(i).toString());
                            break;
                        }
                    default:
                        break;
                }
                
                
            }
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        TweetDataBase a = new TweetDataBase();
            ArrayList<Tweets> loadDBTweets = a.loadDBTweets();
            
            PieChart pie = new PieChart();
            
            pie.createGraphics(loadDBTweets);
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        final StatisticalBarChart demo = new StatisticalBarChart(
            "Statistical Bar Chart Demo"
        );
        demo.pack();
        RefineryUtilities.centerFrameOnScreen(demo);
        demo.setVisible(true);
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Apps().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Tresult;
    private javax.swing.JButton button;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Choice choice2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jitem;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField numberOfTweet;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelG;
    // End of variables declaration//GEN-END:variables
}
